# Generated by Django 3.2.4 on 2021-07-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20210711_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='specialti',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='specialty',
            field=models.ManyToManyField(related_name='vacancies', to='vacancies.Specialty'),
        ),
    ]
