# Generated by Django 3.2.4 on 2021-08-19 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0007_alter_application_written_cover_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('surname', models.CharField(max_length=127)),
                ('salary', models.IntegerField()),
                ('education', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=511)),
                ('link', models.URLField()),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='vacancies.qualification')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty', to='vacancies.specialty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('work_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_status', to='vacancies.workstatus')),
            ],
        ),
    ]
